---
development:
  cloud_name: deqxcyht0
  api_key: '173132313563237'
  api_secret: gmKZYQwN9r8WKccKO4lYXr393aA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: deqxcyht0
  api_key: '173132313563237'
  api_secret: gmKZYQwN9r8WKccKO4lYXr393aA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: deqxcyht0
  api_key: '173132313563237'
  api_secret: gmKZYQwN9r8WKccKO4lYXr393aA
  enhance_image_tag: true
  static_file_support: false
